### ISSUE TITLE
this.document returns undefined

### ISSUE THREAD

**Issue by novyboy** [Polight/lego#32]
Within the Lego.js documentation, it specifies that you can get access to the DOM via the `this.document` shortcut, but when I try to use it, it always returns `undefined`. If I could just use `this.shadowRoot` as I can in vanilla web components, this wouldn't be a problem, but that returns `null`.

**Comment by vinyll** [comment]
Hey @novyboy,
Both `this.document` and the native`this.shadowRoot` should work.
In order to understand, [this is the code where it happens](https://github.com/Polight/lego/blob/master/src/lib/Component.js#L22).

Can you provide more context of the code where you implement this?
If even this.shadowRoot does not exist, I suspect your context is outside of a webcomponent.

**Comment by novyboy** [comment]
Hi @vinyll! Sorry for the late reply.
Within my `web-component.html`, below my template and style tags, I have the following script tag:
```
<script type="module">
	export default class extends Lego {
		init() {
			console.log(this.document);
		}
	}
</script>
```
And if I substitute `this.document` with `this.shadowRoot`, the aforementioned result occurs. 
Is `init()` the wrong place for this kind of logic?

**Comment by vinyll** [comment]
Hey @novyboy,

Indeed `this.document` is not available from `init()` as `init()` is called **before** declaring `this.document`: https://github.com/Polight/lego/blob/master/src/lib/Component.js#L19
The reason is that `init()` is where you would tune your config and declare wether you want to use your shadowDOM or whiteDOM.

Feel free to post here your use case and we could implement something accordingly if it is appropriate.

side node: 
`<script type="module">` could be written `<script>` and will use the _module_ anyways.

**Comment by novyboy** [comment]
Ah~! Thanks so much @vinyll—that clarifies a bunch! 

Then, looking at the code, I'm assuming I could use `connected()` just like `connectedCallback()`? Sweet!

I wasn't sure since I could find the Lego.js-equivalent functions inside the documentation.
